name = "test project"

[[boards]]
name = "Feather RP2040"
manufacturer = "Adafruit"
standard = "Feather"
cpu = "Cortex-M0"
ram = 264
flash = 8000

[[boards]]
name = "Feather nRF52840 Express"
manufacturer = "Adafruit"
standard = "Feather"

[[boards]]
name = "Feather RP2040"
manufacturer = "Adafruit"
standard = "Feather"
cpu = "Cortex-M0"
ram = 264
flash = 8000
